name: first workflow
on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: "this is version name for github workflow"
#  push:
#    branches:
#     -"main"
#  pull_request:
#    branches:
#     -"feature"
#    types: [opened, closed]
jobs:
  first-workflow-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: before checkout action
        run: ls
        shell: bash

      - name: checkout steps
        uses: actions/checkout@v3

      - name: after checkout action
        run: ls
        shell: bash